### ISSUE TITLE
missing entries

### ISSUE THREAD

**Issue by shantanuo** [usernamekiran/mediawiki-bots#1]
I do not see the following entries in the script.

			('अंथरूणा', 'अंथरुणा'),
			(' अंथरुण ', ' अंथरूण '),
			('अपशकूना', 'अपशकुना'),
			(' अपशकुन ', ' अपशकून '),
			('अपीला', 'अपिला'),
			(' अपिल ', ' अपील '),
			('अमीरा', 'अमिरा'),
			(' अमिर ', ' अमीर '),
			('अशीला', 'अशिला'),
			(' अशिल ', ' अशील '),
			('असूडा', 'असुडा'),
			(' असुड ', ' असूड '),
			('वडीला', 'वडिला'),
			(' वडिल ', ' वडील '),
			('कंजूसा ', 'कंजुसा'),
			(' कंजुस ', ' कंजूस '),
			('कंदीला ', 'कंदिला'),
			(' कंदिल ', ' कंदील '),
			('काँक्रीटा', 'काँक्रिटा'),
			(' काँक्रिट ', ' काँक्रीट '),
			('कारकूना', 'कारकुना'),
			(' कारकुन ', ' कारकून '),
			('कारखानीसा', 'कारखानिसा'),
			(' कारखानिस ', ' कारखानीस '),
			('कारागीरा', 'कारागिरा'),
			(' कारागिर ', ' कारागीर '),
			(' वीटा', ' विटा'),
			(' वीटे', ' विटे'),
			(' विट ', ' वीट '),
			('कीटा', 'किटा'),
			(' किट  ', ' कीट '),
			('कीसा', 'किसा'),
			(' किस ', ' कीस '),
			('कूटा', 'कुटा'),
			(' कुट ', ' कूट '),
			('कूडा', 'कुडा'),
			(' कुड ', ' कूड '),
			('कूला', 'कुला'),
			(' कुल ', ' कूल '),
			('कुलूपा  ', 'कुलुपा'),
			(' कुलुप ', ' कुलूप '),
			('कूळा', 'कुळा'),
			(' कुळ ', ' कूळ '),

**Comment by usernamekiran** [comment]
yes. I created the "base file" which was perfect. We can move forward with this base file as a reference point.

**Comment by usernamekiran** [comment]
added the entries to the this file, and script as well.
